devtools をローカルファイル対応にする記述追加
vuejs-miyazaki/vue-hands-on-beginner pull request #5
Opened 2019-01-25 04:33 UTC by mjcreativelab

README に標題の件、追記しました！

2019-01-25 14:28 UTC, hiro0218 requested changes
@mjcreativelab サジェスト機能を使ってみたいがために多めに修正案を出してみています :P

2019-01-25 14:28 UTC, hiro0218 commented on README.md
> +**Vue 用デバッガ**：[Vue.js devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=ja) for Chrome or Firefox
```suggestion
**Vue 用デバッガ**：Vue.js devtools for [Chrome](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=ja) or [Firefox](https://addons.mozilla.org/ja/firefox/addon/vue-js-devtools/)
```

Firefoxのリンクも貼った方が良いかと思いました。

2019-01-25 14:28 UTC, hiro0218 commented on README.md
> +※ インストールしたら **devtools** の詳細設定で「ファイルの URL へのアクセスを許可する」を ON にしてください。
```suggestion
- Vue.jsの製品版または縮小版のビルドを使用している場合、devtoolsのVueペインは表示されません
- Chromeの場合、ローカル(file://)環境でVue.js devtoolsを有効にするには機能するようにするには、Chromeの拡張機能管理の設定で「ファイルの URL へのアクセスを許可する」を ON にしてください
```

製品ビルド版の使用時の注意文言を追加、Firefoxではローカルでの使用許可設定は不要なのでChromeな旨を追加しました。
いかがでしょうか？

2019-01-28 01:38 UTC, Oyanagi-Jotaro-Aratana approved these changes
レビューありがとうございます！
ご指摘の点、その通りだと思います！

2019-01-28 02:06 UTC, mjcreativelab commented
@hiro0218 修正いただいた点、commit させていただきました！
他、問題なければ merge お願いします！

2019-01-28 03:18 UTC, hiro0218 approved these changes
LGTM！

2019-01-28 03:18 UTC, merged